version: '3.9'

services:
  postgres-auth-weather:
    image: postgres:15.1-alpine
    container_name: postgres-auth-weather
    restart: always
    ports:
      - $DB_PORT:5432
    environment:
      - POSTGRES_DB=$DB_DATABASE
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./pg_data/auth-weather:/var/lib/postgresql/data

  redis-auth-weather:
    image: redis:7.0.6-alpine
    container_name: redis-auth-weather
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - $REDIS_PORT:6379
    volumes:
      - ./redis_data:/var/lib/redis/data

  rabbitmq:
    image: rabbitmq:3.11.4-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
    ports:
      - $RABBITMQ_PORT:5672
      - 15672:15672
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq/

volumes:
  redis_data:
    driver: local
  pg_data:
    driver: local
  rabbitmq_data:
    driver: local
